<html>
<head>
<title>DanielAndre REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>DanielAndre REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Basket</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/basket/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/basket/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/basket/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/basket/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/basket/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Basket_Item</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/basket_item/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/basket_item/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/basket_item/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/basket_item/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/basket_item/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Category</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/category/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/category/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/category/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/category/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/category/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Gift_List</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/gift_list/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/gift_list/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/gift_list/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/gift_list/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/gift_list/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Gift_List_Items</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/gift_list_items/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/gift_list_items/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/gift_list_items/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/gift_list_items/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/gift_list_items/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Image</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/image/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/image/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/image/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/image/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/image/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Item</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/item/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/item/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/item/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/item/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/item/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Partner</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/partner/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/partner/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/partner/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/partner/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/partner/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Purchased</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/purchased/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/purchased/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/purchased/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/purchased/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/purchased/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Purchased_Item</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/purchased_item/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/purchased_item/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/purchased_item/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/purchased_item/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/purchased_item/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>User</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/user/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/user/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/user/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/user/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/user/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Wedding</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/wedding/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/wedding/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/wedding/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/wedding/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/wedding/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
